Extractor Comparison Update
utiasASRL/pyboreas pull request #59
Opened 2024-12-17 16:46 UTC by ElliotP-K

-Added code to parse sequence names from files where the results of extractor parameter sweeps are stored
   -EX: 'boreas-2021-10-15-12-35_kstrongest_3_0f35.txt' (result from sweep) -> 'boreas-2021-10-15-12-35.txt' (ground truth)
- Updated aeva data dimension

2025-01-10 16:05 UTC, lisusdaniil commented on pyboreas/eval/odometry.py
> +    # Addition to filter parameter specific sequence to regular sequence ground truth
I am not sure I fully understand whats happening here. Is this just to allow evaluation of folders if the "boreas-xxxx-xx-xx-xx" format now has something appended using an underscore at the end? If so, this needs to be commented better to show the purpose of this.

2025-01-10 16:06 UTC, lisusdaniil commented on pyboreas/eval/odometry.py
> +    # Addition to filter parameter specific sequence to regular sequence ground truth
Also, remove commented out lines of the old way things were written.

2025-01-10 16:07 UTC, lisusdaniil commented on pyboreas/eval/odometry.py
> +    return t_err, r_err, t_re_rmse, t_re_rmse_99f9
This is not backward compatible. People might be using the "eval_odom" function elsewhere and their code will break if additional returns are now returned by default. Also, we didn't find much use for the RMSE right? Maybe no need to integrate this in the public codebase.

2025-01-10 16:08 UTC, lisusdaniil commented on pyboreas/utils/odometry.py
> +        # print(vel_gt_seq[i])
Please remove commented out lines throughout!

2025-01-10 16:11 UTC, lisusdaniil commented on pyboreas/utils/odometry.py
> +    new_segment = False
Not sure this needs to go into the full public codebase either. We also ended up not using this right? Can discuss though.

2025-01-10 16:12 UTC, lisusdaniil commented on pyboreas/utils/odometry.py
> +def plot_stats(seq, dir, T_odom, T_gt, lengths, t_err, r_err, t_re_package):
Same thing here about necessity of this + it not being backward compatible. Please message me to discuss necessity and if we're keeping the changes in utils/odometry.py, they need to be backward compatible (no default expected parameters + default new returns)

2025-01-10 16:20 UTC, lisusdaniil requested changes
Please review comments and msg me about necessity to add many of the new quantitative outputs.

2025-01-11 15:41 UTC, ElliotP-K commented on pyboreas/eval/odometry.py
> +    return t_err, r_err, t_re_rmse, t_re_rmse_99f9
I think this may be on an outdated version of the code I uploaded. I removed all of the additional RMSE and other metrics stuff I played around with over the summer because we ended up just going with the regular KITTI metrics

2025-01-11 15:42 UTC, ElliotP-K commented on pyboreas/utils/odometry.py
> +        # print(vel_gt_seq[i])
Old version I believe, should be gone.

2025-01-11 15:42 UTC, ElliotP-K commented on pyboreas/utils/odometry.py
> +    new_segment = False
Old version I believe, should be gone.

2025-01-11 15:42 UTC, ElliotP-K commented on pyboreas/utils/odometry.py
> +def plot_stats(seq, dir, T_odom, T_gt, lengths, t_err, r_err, t_re_package):
Old version I believe, should be gone.

2025-01-11 15:47 UTC, ElliotP-K commented on pyboreas/eval/odometry.py
> +    # Addition to filter parameter specific sequence to regular sequence ground truth
Yes exactly, it removes anything at the end of the "boreas-xxxx-xx-xx-xx" format.

I added this because for the extractor comparison the folders would now be named something like: "boreas-xxxx-xx-xx-xx_bfar_0f35_20f0" for example. We would need to isolate the original format to get the groundtruth. That is the purpose of this.

This is also an outdated version of the code, the updated version has a comment as follows, LMK if this is adequate:
"# For sequences where there are extractor specific parameters in the name"
"# Ex: 'boreas-2021-10-15-12-35_kstrongest_3_0f35.txt' -> 'boreas-2021-10-15-12-35.txt'"

2025-01-15 15:51 UTC, lisusdaniil approved these changes

2025-01-15 15:51 UTC, merged